package properties

const S3bucketJackalope = "sps-build-deploy"
const S3bucketMasterTempletes = "dev-master-templates-xml"

const Token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpZCI6Ijg0Nzc2ODM0NzAwNjI4NDY2ODg0NTg4MDAyOTQ1NjE1NjI3OTMiLCJlbWFpbCI6Im1wYXNodXJhQHNwc2NvbW1lcmNlLmNvbSIsImZpcnN0X25hbWUiOiJOaWtpdGEiLCJsYXN0X25hbWUiOiJQYXNodXJhIiwiYXZhdGFyX2ltYWdlX3VybCI6IiIsInVzZXJfaWQiOiIxMDg0NzEwNzY3MzYwNDYzNzExMTQzNDc0NzE5ODQyOTI4Mzc5NDciLCJvcmdfaWQiOiIyMDkwOTg4MDgzMDU1NjI0NDY4MTEyNjUzNDEwMzM0NTMwMTU3MDMiLCJvcmdfbmFtZSI6IlNQUyBDb21tZXJjZSIsImV4cCI6MTU0NzAzMTE1OCwidmVyIjoiMSIsImVudiI6ImRldiIsInVyaSI6Imh0dHBzOi8vZGV2LmlkLnNwc2MuaW8iLCJpYXQiOjE1NDY5NDQ3NTh9.Lxcya2fSh-codadXoHmZ2JWOqqckkRcbeLftbq9IMM6GcL2W6WDEL761HCRstLI_btwoZo02qb7xDv6kup5YCVbpSuKMK3Hu3UDM0q3UrsWDNp4bZRCcRCdXa88IiP-HgizYfZ5TBQJ4KmzT-MqZF-h9lw2ThtF4g7LYoZMdyVPLMCowKt-Bo8gwAJyTjeu7fcm6Q-E-ZYluCC00LKLBrO8BTfgluHY8jMgTc4VtdIFgu6yjQkYY4twyKqH6_LPJFMJoem6Xq6IqvEkzkbHmmoh0ZmfcuNVQpu5PTPneSb8xgr98QVnDzkzIVI3tmVatFITFHfluAL4QQs0_vebcSw"

var Format string
var Version string
var Document string

var SchemaKey string
var EnumKey string
